name: CI stub (Hugo)
on:
    push: 
        branches: [ main ]
jobs: 
    hugo-test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: german-revision-helper
        permissions: 
            contents: read
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - name: Setup Hugo extended
              uses: peaceiris/actions-hugo@v3
              with:
                hugo-version: '0.128.2'
                extended: true
            - name: Show Hugo version
              run: |
                hugo version
                command -v hugo


